### ISSUE TITLE
Cannot use craft

### ISSUE THREAD

**Issue by svg-rs** [js802025/calcmod#21]
`[20:10:05] [Server thread/INFO] [calcmod]: Expression: minecraft ID:minecraft:golden_axe
[20:10:05] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: calc craft minecraft piston 120
java.lang.NullPointerException: null
        at net.jsa2025.calcmod.commands.subcommands.Craft.execute(Craft.java:37) ~[Craft.class:forge-1.12.2-1.3.0]
        at net.jsa2025.calcmod.commands.CalcCommand.execute(CalcCommand.java:147) ~[CalcCommand.class:forge-1.12.2-1.3.0]
        at com.feed_the_beast.ftbutilities.ranks.CommandOverride.execute(CommandOverride.java:83) ~[CommandOverride.class:?]
        at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]`

[latest.log](https://github.com/js802025/calcmod/files/13495323/latest.log)

**Comment by js802025** [comment]
what was the exact command that triggered this?

**Comment by js802025** [comment]
I'm closing this issue as it appears to have gone inactive. Feel free to reopen if the problem persists.
