### ISSUE TITLE
Minecraft crashes when I send a command

### ISSUE THREAD

**Issue by FornoContento** [js802025/calcmod#31]
I'm playing Minecraft version 1.20.6 and as soon as I send a command for example ''/calc craft chest 20'' Minecraft simply closes. Here is the Crash Report: 

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-05-31 11:52:10
Description: keyPressed event handler

java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_1860.method_8110(net.minecraft.class_5455)'
	at net.jsa2025.calcmod.commands.subcommands.Craft.execute(Craft.java:83)
	at net.jsa2025.calcmod.commands.subcommands.Craft.lambda$register$0(Craft.java:49)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at com.mojang.brigadier.context.ContextChain.executeAll(ContextChain.java:88)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:228)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:179)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:144)
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:85)
	at net.minecraft.class_634.handler$zii000$fabric-command-api-v2$onSendCommand(class_634.java:3556)
	at net.minecraft.class_634.method_45730(class_634.java)
	at net.minecraft.class_408.method_44056(class_408.java:258)
	at net.minecraft.class_408.method_25404(class_408.java:103)
	at net.minecraft.class_309.method_1454(class_309.java:418)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_309.method_1466(class_309.java:414)
	at net.minecraft.class_309.method_22678(class_309.java:503)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:503)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.jsa2025.calcmod.commands.subcommands.Craft.execute(Craft.java:83)
	at net.jsa2025.calcmod.commands.subcommands.Craft.lambda$register$0(Craft.java:49)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at com.mojang.brigadier.context.ContextChain.executeAll(ContextChain.java:88)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:228)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:179)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:144)
	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:85)
	at net.minecraft.class_634.handler$zii000$fabric-command-api-v2$onSendCommand(class_634.java:3556)
	at net.minecraft.class_634.method_45730(class_634.java)
	at net.minecraft.class_408.method_44056(class_408.java:258)
	at net.minecraft.class_408.method_25404(class_408.java:103)
	at net.minecraft.class_309.method_1454(class_309.java:418)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_309.method_1466(class_309.java:414)
	at net.minecraft.class_309.method_22678(class_309.java:503)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:503)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_309.method_1466(class_309.java:414)
	at net.minecraft.class_309.method_22678(class_309.java:503)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:503)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:218)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 123.784s
	Wall uptime: 112.580s
	High-res time: 110.455s
	Client ticks: 2034 ticks / 101.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['CoccoBruttoGG'/6, l='ClientLevel', x=171.66, y=78.00, z=-226.75]]
	Chunk stats: 4096, 1261
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,79,0), Section: (at 0,15,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5889252 game time, 7275230 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 407

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, boxlib, calcmod, cardinal-components-base, cardinal-components-entity, debugkeybind, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, modmenu, skinlayers3d, sodium, trade_cycling, trinkets, xaerominimap, xaeroworldmap

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1407245840 bytes (1342 MiB) / 2919235584 bytes (2784 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5585
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34725.46
	Virtual memory used (MB): 16309.94
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		boxlib: BoxLib 13.0.2
		calcmod: CalcMod fabric-1.20.2-1.3.1
			clientarguments: clientarguments 1.6
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		clumps: Clumps 17.0.0.1
		collective: Collective 7.58
		debugkeybind: DebugKeybind 8.0.0
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.0.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.99.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.4+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.0+70fd1b46b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.0+a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.1+8e8943b6b0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.39+aae0949ab0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11+a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.16+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0+a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.73+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		iris: Iris 1.7.0+mc1.20.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.6
		modmenu: Mod Menu 10.0.0-beta.1
		skinlayers3d: 3d-Skin-Layers 1.6.5
		sodium: Sodium 0.5.8+mc1.20.6
		trade_cycling: Trade Cycling 1.20.6-1.0.11
		treeharvester: Tree Harvester 8.9
		trinkets: Trinkets 3.9.0
			cardinal-components-base: Cardinal Components API (base) 6.0.0-beta.3
			cardinal-components-entity: Cardinal Components API (entities) 6.0.0-beta.3
		xaerominimap: Xaero's Minimap 24.1.4
		xaeroworldmap: Xaero's World Map 1.38.6
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.15.11-1.20.6
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.85, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 18/18 chunks
	Resource Packs: vanilla, fabric, boxlib, calcmod, cardinal-components-base, cardinal-components-entity, debugkeybind, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, modmenu, skinlayers3d, sodium, trade_cycling, trinkets, xaerominimap (incompatible), xaeroworldmap (incompatible)
	Current Language: en_us
	Locale: it_IT
	CPU: 16x Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['CoccoBruttoGG'/6, l='ServerLevel[New World]', x=171.66, y=78.00, z=-226.75]]
	Active Data Packs: vanilla, fabric, collective, fabric-convention-tags-v2, trinkets, file/BlazeandCave's Advancements Pack 1.16.9.zip, file/Villager cure discount stacking.zip (incompatible)
	Available Data Packs: bundle, collective, fabric, fabric-convention-tags-v2, file/BlazeandCave's Advancements Pack 1.16.9.zip, file/Villager cure discount stacking.zip (incompatible), trade_rebalance, trinkets, update_1_21, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 60843760024901853

**Comment by js802025** [comment]
This has been fixed in the latest beta, which should be available on modrinth here: https://modrinth.com/mod/calcmod/version/cYbHF2E2. Please let me know if this works.
